packages:
  - webview-ui

catalogs:
  build:
    '@tomjs/vscode-extension-webview': ^2.0.0
    '@tomjs/vscode-webview': ^2.0.2
    '@vitejs/plugin-vue': ^6.0.0
    '@vitejs/plugin-vue-jsx': ^5.0.1
    tsdown: ^0.12.9
    unocss: ^66.3.2
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.8.0
    vite: npm:rolldown-vite@latest

  dev:
    '@antfu/eslint-config': ^4.16.2
    '@antfu/ni': ^25.0.0
    '@vscode/vsce': ^3.6.0
    bumpp: ^10.2.0
    eslint: ^9.30.1
    esno: ^4.8.0
    pnpm: ^10.12.4
    reactive-vscode: ^0.3.0
    typescript: ^5.8.3
    vscode-ext-gen: ^1.1.0

  frontend:
    '@vueuse/core': ^13.4.0
    dayjs: ^1.11.13
    naive-ui: ^2.42.0
    vue: ^3.5.17

  types:
    '@types/node': ^24.0.10
    '@types/vscode': ^1.101.0

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
