packages:
  - webview-ui

catalogs:
  build:
    '@tomjs/vscode-extension-webview': ^2.0.0
    '@tomjs/vscode-webview': ^2.0.2
    '@vitejs/plugin-vue': ^5.2.4
    '@vitejs/plugin-vue-jsx': ^4.2.0
    tsdown: ^0.12.8
    unocss: ^66.2.3
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.7.0
    vite: npm:rolldown-vite@latest

  dev:
    '@antfu/eslint-config': ^4.16.1
    '@antfu/ni': ^25.0.0
    '@vscode/vsce': ^3.5.0
    bumpp: ^10.2.0
    eslint: ^9.29.0
    esno: ^4.8.0
    pnpm: ^10.12.2
    reactive-vscode: ^0.3.0
    typescript: ^5.8.3
    vscode-ext-gen: ^1.0.2

  frontend:
    '@vueuse/core': ^13.4.0
    dayjs: ^1.11.13
    naive-ui: ^2.42.0
    vue: ^3.5.17

  types:
    '@types/node': ^24.0.3
    '@types/vscode': ^1.101.0

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
